name: task
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  get: ^4.7.2
  flutter_bloc: ^9.1.1
  retrofit: ^4.4.2
  json_annotation: ^4.8.1
  dio: ^5.8.0+1
  flutter_dotenv: ^5.2.1
  get_it: ^8.0.3
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  retrofit_generator: '>=8.0.0 <10.0.0' # for Dart 3.3 use ^9.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - .env
